# Generated by Django 2.2.4 on 2020-10-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_method',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Payment method ID'),
        ),
    ]
