# Generated by Django 2.2.4 on 2020-06-25 17:36

import django.contrib.postgres.fields
from django.db import migrations
import internationalflavor.countries.models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='countries',
            field=django.contrib.postgres.fields.ArrayField(base_field=internationalflavor.countries.models.CountryField(verbose_name='country'), blank=True, default=list, size=50, verbose_name='countries'),
        ),
    ]
