# Generated by Django 2.2.4 on 2020-06-25 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20200625_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ('fee',), 'verbose_name': 'shipping', 'verbose_name_plural': 'shippings'},
        ),
        migrations.AlterField(
            model_name='shipping',
            name='fee',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, default=None, help_text='EUR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fee'),
        ),
    ]
