# Generated by Django 2.2.4 on 2020-06-25 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20200625_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_fee',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, help_text='EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='payment fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.PositiveSmallIntegerField(db_index=True, unique=True, verbose_name='number'),
        ),
    ]
