# Generated by Django 2.2.4 on 2020-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_auto_20200625_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='quantity'),
        ),
    ]
