# Generated by Django 2.2.4 on 2020-07-02 12:26

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0013_auto_20200626_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title',), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title',), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.Payment', verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_option',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.Shipping', verbose_name='shipping option'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='commerce_pa_i18n_b04da9_gin'),
        ),
        migrations.AddIndex(
            model_name='shipping',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='commerce_sh_i18n_34b55b_gin'),
        ),
    ]
