# Generated by Django 2.2.4 on 2020-07-02 15:12

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('commerce', '0014_auto_20200702_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='title')),
                ('i18n', modeltrans.fields.TranslationField(fields=('title',), required_languages=(), virtual_fields=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'ordering': ('title',),
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='commerce_op_i18n_7d98ad_gin'),
        ),
    ]
