# Generated by Django 2.2.4 on 2020-07-02 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_auto_20200702_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.Option'),
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
