# Generated by Django 2.2.4 on 2020-07-06 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_auto_20200705_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('valid_until',), 'verbose_name': 'discount', 'verbose_name_plural': 'discounts'},
        ),
    ]
