# Generated by Django 2.2.4 on 2020-07-07 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_auto_20200707_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='usage',
            field=models.CharField(choices=[('ONE_TIME', 'one-time only'), ('INFINITE', 'infinite')], default='INFINITE', max_length=8, verbose_name='usage'),
            preserve_default=False,
        ),
    ]
