# Generated by Django 2.2.4 on 2020-07-07 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0023_auto_20200707_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
    ]
