# Generated by Django 2.2.4 on 2020-07-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('commerce', '0025_auto_20200707_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'supply',
                'verbose_name_plural': 'supplies',
                'ordering': ('datetime',),
            },
        ),
    ]
