# Generated by Django 2.2.4 on 2020-07-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='valid_until',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='valid until'),
        ),
    ]
