# Generated by Django 2.2.4 on 2020-07-10 10:14

from django.db import migrations
import internationalflavor.countries.models
import pragmatic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0027_auto_20200708_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='countries',
            field=pragmatic.fields.ChoiceArrayField(base_field=internationalflavor.countries.models.CountryField(verbose_name='country'), blank=True, default=list, size=50, verbose_name='countries'),
        ),
    ]
