# Generated by Django 2.2.4 on 2020-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_auto_20200723_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING', 'Pending'), ('PAYMENT_RECEIVED', 'Payment received'), ('PROCESSING', 'Processing'), ('AWAITING_FULFILLMENT', 'Awaiting Fulfillment'), ('AWAITING_SHIPMENT', 'Awaiting Shipment'), ('AWAITING_PICKUP', 'Awaiting Pickup'), ('PARTIALLY_SHIPPED', 'Partially Shipped'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('DISPUTED', 'Disputed'), ('ON_HOLD', 'On hold')], max_length=20, verbose_name='status'),
        ),
    ]
