# Generated by Django 2.2.4 on 2020-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0033_auto_20200823_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='full name or company name'),
        ),
    ]
