# Generated by Django 2.2.4 on 2020-09-10 10:14

from django.db import migrations
import internationalflavor.countries.models
import pragmatic.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0035_rename_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingoption',
            name='countries',
            field=pragmatic.fields.ChoiceArrayField(base_field=internationalflavor.countries.models.CountryField(verbose_name='country'), blank=True, default=list, size=100, verbose_name='countries'),
        ),
    ]
