# Generated by Django 2.2.4 on 2020-09-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0036_auto_20200910_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='loyalty_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='loyalty points'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='loyalty points'),
        ),
    ]
