# Generated by Django 2.2.4 on 2020-10-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0037_auto_20200927_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'get_latest_by': 'datetime', 'ordering': ('datetime',), 'verbose_name': 'supply', 'verbose_name_plural': 'supplies'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='loyalty_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='used to lower the total price', verbose_name='loyalty points'),
        ),
        migrations.AlterField(
            model_name='order',
            name='loyalty_points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='used to lower the total price', verbose_name='loyalty points'),
        ),
    ]
