# Generated by Django 2.2.4 on 2020-11-30 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0041_auto_20201113_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='products',
            field=gm2m.fields.GM2MField(blank=True, related_name='discounts', through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'), verbose_name='products'),
        ),
    ]
