# Generated by Django 2.2.9 on 2020-12-07 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0043_auto_20201130_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.SmallIntegerField(default=1, verbose_name='quantity'),
        ),
    ]
