# Generated by Django 2.2.9 on 2021-01-02 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0045_auto_20201207_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='option',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='commerce.Option'),
        ),
    ]
