# Generated by Django 2.2.14 on 2021-11-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0046_auto_20210102_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='max_items',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='max items in cart'),
        ),
    ]
