# Generated by Django 2.2.14 on 2021-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0048_auto_20211113_1149'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='discount',
            name='percentage',
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('amount__gte', 0), ('amount__lte', 100), ('unit', 'PERCENTAGE')), ('unit', 'CURRENCY'), _connector='OR'), name='percentage'),
        ),
    ]
