# Generated by Django 3.1.14 on 2022-04-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0049_auto_20211113_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoices',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='invoicing.Invoice', verbose_name='invoices'),
        ),
    ]
