# Generated by Django 4.2.11 on 2025-02-03 13:49

from django.db import migrations, models
import gm2m.fields
import internationalflavor.countries.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('commerce', '0050_auto_20220426_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=gm2m.fields.GM2MField(blank=True, related_name='discounts', through_fields=['gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'], verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_country',
            field=internationalflavor.countries.models.CountryField(blank=True, db_index=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='full name or company name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=30, verbose_name='postcode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='street and number'),
        ),
    ]
