# Generated by Django 2.2.4 on 2020-08-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalpayments', '0002_auto_20200826_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'created', 'ordering': ('created',), 'verbose_name': 'order', 'verbose_name_plural': 'order'},
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=20, verbose_name='operation')),
                ('ordernumber', models.PositiveIntegerField(verbose_name='order number')),
                ('meordernum', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='my order number')),
                ('md', models.CharField(blank=True, default='', max_length=255, verbose_name='md')),
                ('prcode', models.PositiveIntegerField(verbose_name='primary code')),
                ('srcode', models.PositiveIntegerField(verbose_name='secondary code')),
                ('resulttext', models.CharField(blank=True, default='', max_length=255, verbose_name='result text')),
                ('userparam1', models.CharField(blank=True, default='', max_length=64, verbose_name='user param 1')),
                ('addinfo', models.CharField(blank=True, default='', max_length=255, verbose_name='additional information')),
                ('token', models.CharField(blank=True, default='', max_length=64, verbose_name='token')),
                ('expiry', models.CharField(blank=True, default='', max_length=4, verbose_name='expiration')),
                ('acsres', models.CharField(blank=True, default='', max_length=1, verbose_name='authorisation centre result')),
                ('accode', models.CharField(blank=True, default='', max_length=6, verbose_name='authorisation centre code')),
                ('panpattern', models.CharField(blank=True, default='', max_length=19, verbose_name='masked card number')),
                ('daytocapture', models.CharField(blank=True, default='', max_length=8, verbose_name='day to capture')),
                ('tokenregstatus', models.CharField(blank=True, default='', max_length=10, verbose_name='token registration status')),
                ('acrc', models.CharField(blank=True, default='', max_length=2, verbose_name='authorisation centre result code')),
                ('rrn', models.CharField(blank=True, default='', max_length=12, verbose_name='retrieval reference number')),
                ('par', models.CharField(blank=True, default='', max_length=29, verbose_name='payment account reference')),
                ('traceid', models.CharField(blank=True, default='', max_length=15, verbose_name='trace ID')),
                ('digest', models.TextField(verbose_name='digest')),
                ('digest1', models.TextField(verbose_name='digest 1')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalpayments.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'results',
                'ordering': ('created',),
                'get_latest_by': 'created',
            },
        ),
    ]
