# Generated by Django 2.2.4 on 2020-08-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalpayments', '0003_auto_20200827_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'created', 'ordering': ('created',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='result',
            name='meordernum',
        ),
        migrations.AddField(
            model_name='result',
            name='merordernum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='merchant order number'),
        ),
    ]
