# Generated by Django 2.2.4 on 2020-08-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalpayments', '0004_auto_20200827_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='accode',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='authorisation centre code'),
        ),
        migrations.AlterField(
            model_name='result',
            name='acrc',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='authorisation centre result code'),
        ),
        migrations.AlterField(
            model_name='result',
            name='acsres',
            field=models.CharField(blank=True, default=None, max_length=1, null=True, verbose_name='authorisation centre result'),
        ),
        migrations.AlterField(
            model_name='result',
            name='addinfo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='additional information'),
        ),
        migrations.AlterField(
            model_name='result',
            name='daytocapture',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='day to capture'),
        ),
        migrations.AlterField(
            model_name='result',
            name='expiry',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='expiration'),
        ),
        migrations.AlterField(
            model_name='result',
            name='md',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='md'),
        ),
        migrations.AlterField(
            model_name='result',
            name='panpattern',
            field=models.CharField(blank=True, default=None, max_length=19, null=True, verbose_name='masked card number'),
        ),
        migrations.AlterField(
            model_name='result',
            name='par',
            field=models.CharField(blank=True, default=None, max_length=29, null=True, verbose_name='payment account reference'),
        ),
        migrations.AlterField(
            model_name='result',
            name='resulttext',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='result text'),
        ),
        migrations.AlterField(
            model_name='result',
            name='rrn',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='retrieval reference number'),
        ),
        migrations.AlterField(
            model_name='result',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='result',
            name='tokenregstatus',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='token registration status'),
        ),
        migrations.AlterField(
            model_name='result',
            name='traceid',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='trace ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='userparam1',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='user param 1'),
        ),
    ]
