# Generated by Django 2.2.4 on 2020-08-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalpayments', '0006_auto_20200829_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='order',
            new_name='payment',
        ),
    ]
